language: android
android:
    components:
        - platform-tools
        - tools
        - build-tools-21.1.1
        - android-21
before_install:
    - echo "Before install stage"
install:
    - echo "Install stage"
    - sudo apt-add-repository ppa:chris-lea/node.js
    - sudo apt-get update
    - sudo apt-get install nodejs
    - sudo npm -g install cordova ionic
before_script:
    - echo "Before script stage"
script:
    - echo "Script stage"
    - gulp
    - ionic start Kimote blank
    - cd Kimote
    - rm -r www
    - git clone -b release —single-branch https://github.com/eftov/Kimote.git
    - cp -r Kimote/www www
    - cp -r Kimote/resources resources
    - rm -r -f Kimote
    - ionic platform add android
    - ionic platform add ios
    - ionic build
after_success:
    - echo "Build succeeded"
after_failure:
    - echo "Build failed"
after_script:
    - echo "Done"
branches:
    only:
        - master
        - release
sudo: required
